### ISSUE TITLE
Update product.json

### ISSUE THREAD

**Issue by soichih** [kitchell/app-testgradientflip#8]
We should update the current product.json output from

```
{
    "recommend": "no flip",
    "noflip": 483408,
    "xflip": 100565,
    "yflip": 204841,
    "zflip": 139850
}
``` 

to

```
{
	"brainlife": [{
			"type": "info",
			"msg": "No flip recommended"
		},
		{
			"type": "plotly",
			"name": "Flip Recommendation",
			"data": {
				"values": [483408, 100565, 204841, 139850],
				"labels": ["noflip", "xflip", "yflip", "zflip"],
				"type": "pie"
			},
			"layout": {}
		}
	]
}
```

So that this information will be displayed right under task Output on BL.

More on product.json > https://brain-life.github.io/docs/apps/product/
Sample Matlab code for generating product.json > https://github.com/brain-life/app-life/blob/master/main.m#L131

**Comment by kitchell** [comment]
if you can make a pull request for this change I can accept it, otherwise it will take a while for me to have time to implement.

**Comment by soichih** [comment]
I've asked @stevengeeky to help us with this.
